POST http://localhost:3003/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV6ZW0iLCJpZCI6IjY3ZjI5ZjY0YjhlNzBmM2JiMGVmMWI3NiIsImlhdCI6MTc0Mzk1MzgxNn0.6L3QD2go8aJKpRmVFEFBZkBaJM7QIpV8wn-0p_Wo-LY

{
  "content": "Token auth rocks!",
  "important": false
}