POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV6ZW0iLCJpZCI6IjY3ZjJhYTkyMWVkMWQ1N2JhMzc3NWNmOCIsImlhdCI6MTc0Mzk1NjY0NX0._3LhYvx91jBFcOTy_0wfV8v_4VjgolnQcFnE4yl_u3g

{
  "content": "Token auth rocks!",
  "important": false
}